### ISSUE TITLE
Write unit tests for libraries

### ISSUE THREAD

**Issue by BYK** [BYK/ES5#2]
All libraries should have unit tests to ensure a bug-free library set.

@burcu said:

> I'm not sure about licensing but V8 has the full functional JS tests under http://code.google.com/p/v8/source/browse#svn/trunk/test/mjsunit, tests related to ES5 features can be extracted from their repo. Licensing should be researched though.

on Google Code project before.

**Comment by berkerpeksag** [comment]
Done.

fe2904448fd4fe504e99107f3e2b3e64d7fa03a8
eae25ffbe3870a991447ef672d226ae1e2a1cdfa
be61d8f712040eaefa30a37298b9f792d3f60d0c
0429330204fa1e51f9902237254b1bd2e34ce159
9ee4b7c60c80a4de40c9a10485dbeb57e8866f81
5e470350a402159941ed5697149500295d3962dc

**Comment by berkerpeksag** [comment]
- Date.now() should be tested too.
- test/unit/Object.js: keys() -> This test does not cover any of the edge cases like "hasOwnProperty" and a possible override of "hasOwnProperty" which our code suffers from =)
- We should test getPrototypeOf too, somehow.
- test/unit/Array.js: map() -> May be we should consider using ".join(',')" for a more explicit concatenation. Also I think we should explicitly check if the returned array is not the same array as the array the method called on since this is important.
- test/unit/Array.js: every() -> 'Testing size of all array elements.' explanation is used almost for every test and it does not explain the test case very good. We should change that.
- test/unit/Array.js: indexOf() -> May be we should check for an element in the middle or in the end. Also we don't check the "fromIndex" parameter and its effect on the result.
- test/unit/Array.js: isArray() -> // All following calls should return true ;)
